name: Playwright Tests

on: 
    push:
        branches: [main, master]
    pull_request: 
        branches: [main, master]

jobs:
    playwright:
        timeout-minutes: 60
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                
            - name: Install packages
              run: npm install    

            - name: Install Playwright browsers
              run: npm install playwright --with-deps  

            - name: Run Playwright tests
              run: npx playwright test 